package rx.enums;

// 过渡显示的效果
	public enum TransitionType {
		RANDOM,BOX_RANDOM,
		MOVE_TO_LEFT, MOVE_TO_RIGHT, MOVE_TO_TOP, MOVE_TO_BOTTOM,
		BOX_TO_LEFT, BOX_TO_RIGHT, BOX_TO_TOP, BOX_TO_BOTTOM,
		LINE_TO_LEFT, LINE_TO_RIGHT, LINE_TO_BOTTOM, LINE_TO_TOP,
		FADE, NONE, CIRCLE, RECTANGLE,GAUSSIAN_BLUR, MOTION_BLUR, BLEND, SECTOR;
	}